version: 2.1
jobs:
  publish:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "Install Jfrog CLI"
      - run: cd ~/repo
      - run: curl -fL https://getcli.jfrog.io | sh
      - run: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password $ARTIFACTORY_PASSWORD --interactive=false
      - run: ./jfrog rt dl "Demo-npm-local/@calvinlauconpm/neon-test/-/" --sort-by=created --sort-order=desc --limit=1
      - run: cd ~/repo && dir
      - run: tar -C ~/ -xvf ~/repo/@calvinlauconpm/neon-test/-/*.tgz
      - run: cp -r ~/package/* ~/repo/
      - run: pwd
      - run: ls -lrt
      - run: ls -lrt ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish npm package
          command: npm publish --access public
orbs:
  slack: circleci/slack@3.4.2
  jira: circleci/jira@1.2.2
workflows:
  your-workflow:
    jobs:
      - publish
